#!/bin/sh

$BLOCK_NAME="xmms2play"
hard_label="\uf2b5"

# Get the playlist size, minus 2 lines which aren't
# the musics in the list.
list_size=$(($(xmms2 list | wc -l) - 2))
if [ $list_size -le 0 ]; then
    echo -e "  ${hard_label}  [No music in xmms2 list]"
    exit 0
fi

# Title of music
# NOTE: I always set the metadata of the music's title, artist and album.
#       The title below uses the `xmms2 current` convention, i.e.
#       "${artist} - ${title}"
title=$(xmms2 current | grep -oE "[[:space:]]\-[[:space:]].+:[[:space:]]" | cut -c '4-')
title=${title%:*}

# Time current and end
time_cur=$(xmms2 current | grep -oE "[0-9]{2}\:[0-9]{2}" | sed -n '1p')
time_end=$(xmms2 current | grep -oE "[0-9]{2}\:[0-9]{2}" | sed -n '2p')

# Status (i.e. paused, playing, stopped)
stat=$(xmms2 current)
stat=${stat%%:*}
if [ $stat = "Playing" ]; then
   hard_label="\uf315"
elif [ $stat = "Paused" ]; then
   hard_label="\uf310"
elif [ $stat = "Stopped" ]; then
   hard_label="\uf34f"
fi

# Config (i.e. repeat all or repeat one or none)
conf_repeat_all=$(xmms2 server config playlist.repeat_all)
conf_repeat_one=$(xmms2 server config playlist.repeat_one)
conf=""

# repeat_one take priority over repeat_all
if [ "$conf_repeat_all" = "playlist.repeat_all = 1" ]; then
    conf="R"
fi
if [ "$conf_repeat_one" = "playlist.repeat_one = 1" ]; then
    conf="r"
fi

echo -e "${hard_label}  " $title \| ${time_cur} / ${time_end} [${conf}]
echo -e "${hard_label}  " $title \| ${time_cur} / ${time_end} [${conf}]

